export default {
    title: "Health Connections Direct Primary Care",
    subtitle: "Primary Care and Immigration Physicals",
    slogan: "Healthcare the way it should be",
    location: "Located in Florence, KY",
    whyDPC: "Why Choose Direct Primary Care?",
    whyDPCText: "Direct Primary Care (DPC) is a healthcare model that puts you first. It allows for a more personalized and accessible relationship with your healthcare provider, without the interference of third-party insurance. By choosing DPC, you'll enjoy transparent pricing, longer appointments, and direct access to your physician. This means more time to discuss your concerns and a tailored health plan that works for you.",
    aboutHCDPC: "About Health Connections DPC",
    aboutHCDPCText: "Health Connections Direct Primary Care, located in the heart of Florence, KY, is your go-to healthcare solution. Since opening in 2017, we've been committed to providing quality care without barriers. Whether you need routine check-ups, basic lab tests, or have unique medical needs, we are here for you. Dr. Villacis's bilingual abilities in English and Spanish ensure that language is never a barrier to your care. Come experience healthcare the way it should be, at Health Connections DPC.",
    services: "Services",
    servicesText: "We offer a wide range of services to meet your healthcare needs. Our services include:",
    servicesList: [
        "Routine check-ups",
        "Basic lab tests",
        "Chronic disease management",
        "Acute illness care",
        "Minor procedures",
    ],
    immigrationText: "We also offer immigration physicals for those seeking to become permanent residents of the United States.",
}